from pathlib import Path

import torch
from transformers import Trainer, TrainingArguments
from peft import LoraConfig, get_peft_model, PeftModel

from .base_llm import BaseLLM
from .sft import test_model, TokenizedDataset, tokenize
from .data import Dataset


class RFTModel(BaseLLM):
    def format_prompt(self, question: str) -> str:
        """
        RFT models are trained on raw questions without chat templates.
        Return the question as-is.
        """
        # code help from ChatGPT
        return (
            f"{question}\n"
            "Show your reasoning step by step and then give only the final "
            "numeric result inside <answer>...</answer>."
        )



def load() -> RFTModel:
    from pathlib import Path

    from peft import PeftModel

    model_name = "rft_model"
    model_path = Path(__file__).parent / model_name

    llm = RFTModel()
    llm.model = PeftModel.from_pretrained(llm.model, model_path).to(llm.device)
    llm.model.eval()

    return llm


def train_model(
    output_dir: str = "./homework/rft_model",
    **kwargs,
):
    # code help from ChatGPT
    # Reuse much of the SFT code here
    # 1) Base RFT LLM
    llm = RFTModel()

    # 2) LoRA config (slightly larger rank than SFT is okay, but keep size < 50MB)
    r = 16
    lora_alpha = 64

    lora_config = LoraConfig(
        r=r,
        lora_alpha=lora_alpha,
        target_modules="all-linear",
        bias="none",
        task_type="CAUSAL_LM",
    )

    lora_model = get_peft_model(llm.model, lora_config)

    # Needed when using gradient checkpointing on GPU
    if hasattr(lora_model, "enable_input_require_grads") and torch.cuda.is_available():
        lora_model.enable_input_require_grads()

    # 3) Load RFT dataset generated by datagen.py (question, correct_answer, cot_text)
    rft_data = Dataset("rft")

    # Small inner formatting function (no extra top-level helpers)
    def format_example_rft(question: str, correct_answer, cot_text: str):
        prompt_text = (
            f"{question}\n"
            "Show your reasoning step by step and then give only the final "
            "numeric result inside <answer>...</answer>."
        )
        return {
            "question": prompt_text,
            "answer": cot_text,
        }

    train_dataset = TokenizedDataset(llm.tokenizer, rft_data, format_example_rft)

    Path(output_dir).mkdir(parents=True, exist_ok=True)

    # 4) TrainingArguments (no evaluation_strategy—your transformers version doesn’t support it)
    training_args = TrainingArguments(
        output_dir=output_dir,
        logging_dir=output_dir,
        report_to=["tensorboard"],
        per_device_train_batch_size=32,
        num_train_epochs=5,
        learning_rate=5e-5,
        gradient_checkpointing=True,
        save_strategy="epoch",
        logging_steps=50,
        fp16=torch.cuda.is_available(),
    )

    # 5) Trainer
    trainer = Trainer(
        model=lora_model,
        args=training_args,
        train_dataset=train_dataset,
    )

    trainer.train()
    trainer.save_model(output_dir)

    # Optional sanity check using the existing SFT test harness
    test_model(output_dir)


if __name__ == "__main__":
    from fire import Fire

    Fire({"train": train_model, "test": test_model, "load": load})
